functionsDirectory = "D:\\项目\\ai测试\\netlify\\functions"
functionsDirectoryOrigin = "default"
headersOrigin = "config"
plugins = []
redirects = []

[build]
publish = "D:\\项目\\ai测试"
publishOrigin = "config"
functions = "D:\\项目\\ai测试\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"